default: &default
  adapter: postgresql
  encoding: SQL_ASCII
  pool: 5
  username: ubuntu
  password: password

development:
  <<: *default
  database: tutor

test:
  <<: *default
  database: tutor

production:
  <<: *default
  encoding: unicode
  database: tutor